apiVersion: v1
kind: Pod
metadata:
  name: standlone
  namespace: roboshop
  labels:
    name: standlone
    project: roboshop
spec:
  containers:
  - name: standlone
    image: karunakar2000/standlone:v3
    imagePullPolicy: Always
